In [44]:
import numpy as np
import pandas as pd

In [3]:
data = pd.read_csv("veriler.csv")

In [4]:
data.head()

ulke  boy  kilo  yas cinsiyet
0   tr  130    30   10        e
1   tr  125    36   11        e
2   tr  135    34   10        k
3   tr  133    30    9        k
4   tr  129    38   12        e

In [9]:
cinsiyet = data.iloc[:,-1:].values #"1den ve 4.sutuna kadar 4 dahil degil" dizi olusturduk

In [10]:
cinsiyet

array([['e'],
       ['e'],
       ['k'],
       ['k'],
       ['e'],
       ['e'],
       ['e'],
       ['e'],
       ['k'],
       ['e'],
       ['k'],
       ['k'],
       ['k'],
       ['k'],
       ['k'],
       ['e'],
       ['e'],
       ['e'],
       ['e'],
       ['k'],
       ['k'],
       ['k']], dtype=object)

In [11]:
from sklearn import preprocessing

In [17]:
le = preprocessing.LabelEncoder()

In [18]:
cinsiyet[:,-1] = le.fit_transform(data.iloc[:,-1])

In [19]:
cinsiyet

array([[0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1]], dtype=object)

In [20]:
c = pd.DataFrame(data = cinsiyet, index = range(22), columns = ["cinsiyet"])

In [12]:
ulke = data.iloc[:,0:1].values

In [13]:
ulke

array([['tr'],
       ['tr'],
       ['tr'],
       ['tr'],
       ['tr'],
       ['tr'],
       ['tr'],
       ['tr'],
       ['tr'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['fr'],
       ['fr'],
       ['fr'],
       ['fr'],
       ['fr'],
       ['fr'],
       ['fr']], dtype=object)

In [21]:
ulke[:,0]=le.fit_transform(data.iloc[:,0])

In [ ]:
ulke

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0]], dtype=object)

In [22]:
ohe = preprocessing.OneHotEncoder()

In [23]:
ulke=ohe.fit_transform(ulke).toarray()

In [24]:
ulke

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [ ]:
#DATAFRAME OLUSTURMA

In [25]:
sonuc = pd.DataFrame(data=ulke,index=range(22),columns=["fr","tr","us"])

In [26]:
sonuc

fr   tr   us
0   0.0  1.0  0.0
1   0.0  1.0  0.0
2   0.0  1.0  0.0
3   0.0  1.0  0.0
4   0.0  1.0  0.0
5   0.0  1.0  0.0
6   0.0  1.0  0.0
7   0.0  1.0  0.0
8   0.0  1.0  0.0
9   0.0  0.0  1.0
10  0.0  0.0  1.0
11  0.0  0.0  1.0
12  0.0  0.0  1.0
13  0.0  0.0  1.0
14  0.0  0.0  1.0
15  1.0  0.0  0.0
16  1.0  0.0  0.0
17  1.0  0.0  0.0
18  1.0  0.0  0.0
19  1.0  0.0  0.0
20  1.0  0.0  0.0
21  1.0  0.0  0.0

In [31]:
sonuc2=pd.DataFrame(data=data.iloc[:,1:4].values,index=range(22),columns=["boy","kilo","yas"])

In [32]:
sonuc2

boy  kilo  yas
0   130    30   10
1   125    36   11
2   135    34   10
3   133    30    9
4   129    38   12
5   180    90   30
6   190    80   25
7   175    90   35
8   177    60   22
9   185   105   33
10  165    55   27
11  155    50   44
12  160    58   39
13  162    59   41
14  167    62   55
15  174    70   47
16  193    90   23
17  187    80   27
18  183    88   28
19  159    40   29
20  164    66   32
21  166    56   42

In [39]:
newData = pd.concat([sonuc,sonuc2],axis=1) #axis=1 satırları eşleme

In [40]:
newData

fr   tr   us  boy  kilo  yas
0   0.0  1.0  0.0  130    30   10
1   0.0  1.0  0.0  125    36   11
2   0.0  1.0  0.0  135    34   10
3   0.0  1.0  0.0  133    30    9
4   0.0  1.0  0.0  129    38   12
5   0.0  1.0  0.0  180    90   30
6   0.0  1.0  0.0  190    80   25
7   0.0  1.0  0.0  175    90   35
8   0.0  1.0  0.0  177    60   22
9   0.0  0.0  1.0  185   105   33
10  0.0  0.0  1.0  165    55   27
11  0.0  0.0  1.0  155    50   44
12  0.0  0.0  1.0  160    58   39
13  0.0  0.0  1.0  162    59   41
14  0.0  0.0  1.0  167    62   55
15  1.0  0.0  0.0  174    70   47
16  1.0  0.0  0.0  193    90   23
17  1.0  0.0  0.0  187    80   27
18  1.0  0.0  0.0  183    88   28
19  1.0  0.0  0.0  159    40   29
20  1.0  0.0  0.0  164    66   32
21  1.0  0.0  0.0  166    56   42

In [42]:
from sklearn.linear_model import LinearRegression

In [43]:
regressor = LinearRegression()

In [66]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(newData,c,test_size=0.33,random_state=0)

In [67]:
regressor.fit(x_train,y_train)

LinearRegression()

In [68]:
y_pred = regressor.predict(x_test)

In [50]:
y_pred

array([[0.01279796],
       [1.12036863],
       [0.94990297],
       [0.92862582],
       [0.27526065],
       [0.35384956],
       [1.03567453],
       [0.67387829]])

In [69]:
y_test

cinsiyet
20        1
10        1
14        1
13        1
1         0
21        1
11        1
19        1

In [78]:
#boy tahmini

boy = data.iloc[:,1:2].values
boy



array([[130],
       [125],
       [135],
       [133],
       [129],
       [180],
       [190],
       [175],
       [177],
       [185],
       [165],
       [155],
       [160],
       [162],
       [167],
       [174],
       [193],
       [187],
       [183],
       [159],
       [164],
       [166]])

In [81]:
boytahminidata=newData.drop(["boy"],axis=1)

In [73]:
c

cinsiyet
0         0
1         0
2         1
3         1
4         0
5         0
6         0
7         0
8         1
9         0
10        1
11        1
12        1
13        1
14        1
15        0
16        0
17        0
18        0
19        1
20        1
21        1

In [83]:
boytahminidata=pd.concat([boytahminidata,c],axis=1)


In [84]:
boytahminidata

fr   tr   us  kilo  yas cinsiyet
0   0.0  1.0  0.0    30   10        0
1   0.0  1.0  0.0    36   11        0
2   0.0  1.0  0.0    34   10        1
3   0.0  1.0  0.0    30    9        1
4   0.0  1.0  0.0    38   12        0
5   0.0  1.0  0.0    90   30        0
6   0.0  1.0  0.0    80   25        0
7   0.0  1.0  0.0    90   35        0
8   0.0  1.0  0.0    60   22        1
9   0.0  0.0  1.0   105   33        0
10  0.0  0.0  1.0    55   27        1
11  0.0  0.0  1.0    50   44        1
12  0.0  0.0  1.0    58   39        1
13  0.0  0.0  1.0    59   41        1
14  0.0  0.0  1.0    62   55        1
15  1.0  0.0  0.0    70   47        0
16  1.0  0.0  0.0    90   23        0
17  1.0  0.0  0.0    80   27        0
18  1.0  0.0  0.0    88   28        0
19  1.0  0.0  0.0    40   29        1
20  1.0  0.0  0.0    66   32        1
21  1.0  0.0  0.0    56   42        1

In [85]:
a_train,a_test,b_train,b_test = train_test_split(boytahminidata,boy,test_size=0.33,random_state=0)

In [102]:
regressor2 = LinearRegression()

In [103]:
regressor2.fit(a_train,b_train)

LinearRegression()

In [104]:
b_pred = regressor2.predict(a_test)

In [105]:
b_pred

array([[182.26638686],
       [152.87161474],
       [162.79386375],
       [158.30668577],
       [130.82888952],
       [173.96138408],
       [150.12782663],
       [157.26898922]])

In [108]:
b_test

array([[164],
       [165],
       [167],
       [162],
       [125],
       [166],
       [155],
       [159]])